---
title: "R Notebook"
output: html_notebook
---
```{r}
library(lmPerm)
library(dplyr)
source("ens_specaccum.R")

final_merged <- read.csv("../final_2018.csv", header = TRUE, stringsAsFactors = FALSE)
head(final_merged)[,1:20]
getwd()
```

```{r}
com.mat <- final_merged %>% select(- one_of("site", "block", "plot", "subplot", "x", "y", 
                                            "note", "index", "year", "sitename", "dateestablished", 
                                            "plotlocation", "fertilized", "X"))
com.attr <-  final_merged %>% select(one_of("site", "block", "plot", "subplot", "x", "y", 
                                            "note", "index", "year", "sitename", "dateestablished", 
                                            "plotlocation", "fertilized"))

dfun = d_calc

com_norm <- normalize_rows(com.mat)
unique(rowSums(com_norm)) == 1

# Sample (alpha) diversity
alpha_q0 = apply(com_norm, 1, dfun, q = 0, sample.weight = 1)
alpha_q1 = apply(com_norm, 1, dfun, q = 1, sample.weight = 1)
alpha_q2 = apply(com_norm, 1, dfun, q = 2, sample.weight = 1)

# Combining alpha statistics to a single dataframe
alpha.stats <- cbind(com.attr, alpha_q0, alpha_q1, alpha_q2) %>% 
  group_by(site, block, plot, fertilized, year) %>%
  summarise_at(c("alpha_q0", "alpha_q1", "alpha_q2"), mean)

alpha.raw <- cbind(com.attr, alpha_q0, alpha_q1, alpha_q2)

# Aggregating to generate gamma diversity matrix
com.gamma <- bind_cols(select(com.attr, site, block, plot, year, fertilized), com.mat) %>% 
  group_by(site, block, plot, year, fertilized) %>%
  summarise_all(sum)

# Generating gamma diversity dataset
gamma.attr <- com.gamma[,1:5]
gamma.norm <- normalize_rows(com.gamma[,-(1:5)])

# Total (gamma) diversity
gamma_q0 = apply(gamma.norm, 1, dfun, q = 0, sample.weight = 1)
gamma_q1 = apply(gamma.norm, 1, dfun, q = 1, sample.weight = 1)
gamma_q2 = apply(gamma.norm, 1, dfun, q = 2, sample.weight = 1)

gamma.stats <- cbind(data.frame(gamma.attr), gamma_q0, gamma_q1, gamma_q2)

# Combining into a single dataframe
alldiv.stats <- inner_join(alpha.stats, gamma.stats) %>%
  mutate(beta_q0 = gamma_q0 / alpha_q0,
         beta_q1 = gamma_q1 / alpha_q1,
         beta_q2 = gamma_q2 / alpha_q2)
```

# Statistical analysis:

## What is the correct model structure:

* Repeated measures (each plot over time)
* Blocking and within-site variance
* Treatment effects (1 and 2 years)
* Treatment treated as linear vs. nonlinear?
* Interannual variation

## I think the most appropriate command is:

* Div ~ treatment x as.factor(year) + (1 | site/block)

# Alpha-scale analysis
```{r}
# Filter out one block at HREC?
alpha.raw <- alpha.raw %>% filter(! ((site == "HREC") & (block == 1))) 
head(alpha.raw)

alpha.raw$site <- as.factor(alpha.raw$site) # Site as factor
alpha.raw$block <- as.factor(alpha.raw$block) # Block as factor
alpha.raw$fert_num <- alpha.raw$fertilized * (alpha.raw$year - 2016)
alpha.raw$fertilized <- as.factor(alpha.raw$fertilized) # Fertilization as factor
alpha.raw$year <- alpha.raw$year - 2016 # Year as range of 1-2
alpha.raw$year <- as.factor(alpha.raw$year) # Y

mod1_q0 <- lmer(alpha_q0 ~ factor(fert_num) + factor(year) + (1|site) + (1|block:site), data = alpha.raw)

summary(mod1_q0)
anova(mod1_q0)
```

```{r}

```


