---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse); library(testthat)

mcla_peak <- read.csv("../Data/2019/Merged_Data/MCLA_Peak_Merged.csv", row.names = 1, stringsAsFactors = FALSE)
mcla_spring <- read.csv("../Data/2019/Merged_Data/MCLA_Spring_Merged.csv", row.names = 1, stringsAsFactors = FALSE)
sfrec_peak <- read.csv("../Data/2019/Merged_Data/SFREC_Peak_Merged.csv", row.names = 1, stringsAsFactors = FALSE)
sfrec_spring <- read.csv("../Data/2019/Merged_Data/SFREC_Spring_Merged.csv", row.names = 1, stringsAsFactors = FALSE)
mcla_late <- read.csv("../Data/2019/Merged_Data/MCLA_Late_Merged.csv", row.names = 1, stringsAsFactors = FALSE)

labels_2019 <- read.csv("../Data/2019/2019_labels.csv", row.names = 1, stringsAsFactors = FALSE)
```


```{r}
fix_names <- function(comm_dat, names_dat){
  
  newdata <- comm_dat[,!(names(comm_dat) %in% names_dat$Name)]
  
  comm_dat[is.na(comm_dat)] = 0
  
  expect_equivalent(ncol(newdata), 6, label = "ID columns are not equal to 6")
  
  names_dat <- names_dat %>% filter(Name %in% colnames(comm_dat))
  
  for(col_name in unique(names_dat$NewName)){
    
    corrected_cols <- comm_dat %>% select(names_dat$Name[names_dat$NewName == col_name])
    
    newcol <- apply(corrected_cols, 1, max)
    
    newdata <- cbind(newdata, newcol)
  
    colnames(newdata)[length(colnames(newdata))] <- col_name
  }
  
  return(newdata)
}

dfs <- list(mcla_peak, mcla_spring, mcla_late, sfrec_peak, sfrec_spring)

corrected_dfs <- lapply(dfs, fix_names,  names_dat = labels_2019)

```

```{r}

merge_max_cover <- function(df1, df2){
  
  expect_equivalent(nrow(df1), nrow(df2), label = "Datasets with different numbers of observations")
  
  matching_cols <- colnames(df1[,-c(1:6)])[colnames(df1[,-c(1:6)]) %in% colnames(df2[,-c(1:6)])]

  merged_data <- left_join(df1[,!(colnames(df1) %in% matching_cols)], df2[,!(colnames(df2) %in% matching_cols)])
  
  for(col_name in matching_cols){
    
    newcol <- apply(cbind(df1[,col_name], df2[,col_name]), 1, max)
    
    merged_data <- cbind(merged_data, newcol)
    
   colnames(merged_data)[length(colnames(merged_data))] <- col_name

  }
  
  return(merged_data)
}


mcla_dfs <- merge_max_cover(df1 = corrected_dfs[[1]], df2 = corrected_dfs[[2]])
mcla_dfs <- merge_max_cover(df1 = mcla_dfs, df2 = corrected_dfs[[3]])

sfrec_dfs <- merge_max_cover(df1 = corrected_dfs[[4]], df2 = corrected_dfs[[5]])

compiled_2019 <- bind_rows(mcla_dfs, sfrec_dfs)
compiled_2019[is.na(compiled_2019)] = 0
compiled_2019 <- compiled_2019 %>% select(c(colnames(compiled_2019)[1:6], 
                                            sort(colnames(compiled_2019)[7:length(colnames(compiled_2019))])))

colnames(compiled_2019) <- tolower(colnames(compiled_2019))

# write.csv("../Data/2019/data2019_combined.csv",
#           x = compiled_2019,
#           row.names = FALSE)
```

# Merging across all years

```{r}
data2019 <- read.csv("../Data/2019/data2019_combined.csv", stringsAsFactors = FALSE)
data2018 <- read.csv("../Data/2018/merged_data_2018_final.csv", stringsAsFactors = FALSE, row.names = 1)
data2017 <- read.csv("../Data/2017/alldatacombined2017.csv", stringsAsFactors = FALSE)

colnames(data2019) <- tolower(colnames(data2019))
colnames(data2018) <- tolower(colnames(data2018))
colnames(data2017) <- tolower(colnames(data2017))

data2017$year <- 2017
data2018$year <- 2018
data2019$year <- 2019

colnames(data2019)[1:6] <- colnames(data2017)[1:6]
colnames(data2018)[1:6] <- colnames(data2017)[1:6]

full_data <- bind_rows(list(data2017, data2018, data2019)) 

full_data[is.na(full_data)] = 0

full_data <- full_data %>% select(c(colnames(data2017[1:6]), year, 
                                            sort(colnames(full_data)[8:length(colnames(full_data))])))

write.csv(full_data,
          "../Data/data_combined_allyears.csv",
          row.names = FALSE)

speclist1 <- read.csv("../Data/SpeciesList.csv", stringsAsFactors = FALSE)
cols <- data.frame(Label = colnames(full_data)[8:length(colnames(full_data))])

write.csv(x = left_join(cols, speclist1, by = "Label"),
          "../Data/data_combined_columndata.csv",
          row.names = TRUE)
```

```{r}
columnids <- read.csv("../Data/ColumnIDs_Final.csv", row.names = 1)

length(unique(columnids$Abbreviaton))
length(unique(columnids$Abbreviaton)) == length(unique(columnids$Taxon))

View(mobr::rarefaction)
?mobr::rarefaction
```

