---
title: "Generating Species Accumulation Curves"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)
source("ens_specaccum.R")

final_merged <- read.csv("../final_2018.csv", header = TRUE, stringsAsFactors = FALSE)
head(final_merged)[,1:20]

com.mat <- final_merged %>% select(- one_of("site", "block", "plot", "subplot", "x", "y", 
                                            "note", "index", "year", "sitename", "dateestablished", 
                                            "plotlocation", "fertilized", "X"))
com.attr <-  final_merged %>% select(one_of("site", "block", "plot", "subplot", "x", "y", 
                                            "note", "index", "year", "sitename", "dateestablished", 
                                            "plotlocation", "fertilized"))
```

# Accumulation at q = 0

```{r}

specaccum <- function(qval){
  
  output <- list(NA)
  counter <- 1
  
  for(SiteName in unique(com.attr$site)){
    for(YearVal in unique(com.attr$year)){
      for(BlockVal in c(1:4)){
        
        # Fertilized spatial aggregation
          F_agg <- jost_specaccum_v2(
              com.data = com.mat[com.attr$site == SiteName &
                                 com.attr$block == BlockVal &
                                 com.attr$year == YearVal &
                                 com.attr$fertilized == 1,],
              com.ids = com.attr[com.attr$site == SiteName &
                                 com.attr$block == BlockVal &
                                 com.attr$year == YearVal &
                                 com.attr$fertilized == 1,],
              q.value = qval,
              spatial.columns = c("x", "y"))
      
        # Unfertilized spatial aggregation
          UF_agg <- jost_specaccum_v2(
              com.data = com.mat[com.attr$site == SiteName &
                                 com.attr$block == BlockVal &
                                 com.attr$year == YearVal &
                                 com.attr$fertilized == 0,],
              com.ids = com.attr[com.attr$site == SiteName &
                                 com.attr$block == BlockVal &
                                 com.attr$year == YearVal &
                                 com.attr$fertilized == 0,],
              q.value = qval,
              spatial.columns = c("x", "y"))
          
          out <- cbind(data.frame(site = rep(as.character(SiteName), 2),
                     block = rep(as.character(BlockVal), 2),
                     year = rep(as.character(YearVal), 2),
                     fert = c(1,0),
                     stat = c("mean", "mean")),
                rbind(F_agg[[1]], UF_agg[[1]]))
          
          output[[counter]] = list(out)
          counter <- counter + 1
      }
    }
  }

  return(output)
}


q0_spatial <- reduce(specaccum(0), bind_rows) %>%
  gather(key = "samp", value = "div", -(1:5)) %>%
  filter(! ((site == "HREC") & (block == 1))) 

calc_diff <- function(x){
  return(data.frame(div_u = x$div[x$fert == 0],
                    div_f = x$div[x$fert == 1],
                    diff = x$div[x$fert == 0] - x$div[x$fert == 1],
                    diff_frac = (x$div[x$fert == 0] - x$div[x$fert == 1]) / x$div[x$fert == 0] ))
  
}

q0_spatial_summary <- q0_spatial %>% group_by(site, block, year, samp) %>%
  do(calc_diff(.))

q0_spatial_summary %>% filter(samp == 1 | samp == 64)

q0_spatial_summary %>%
  ggplot(aes(x = as.numeric(samp))) +
  geom_line(aes(y = -diff_frac, linetype = paste(site, block), color = year)) +
  ggtitle("difference at q = 0")

```

# Accumulation at q = 1

```{r}
q1_spatial <- reduce(specaccum(1), bind_rows) %>%
  gather(key = "samp", value = "div", -(1:5)) %>%
  filter(! ((site == "HREC") & (block == 1))) 

calc_diff <- function(x){
  return(data.frame(div_u = x$div[x$fert == 0],
                    div_f = x$div[x$fert == 1],
                    diff = x$div[x$fert == 0] - x$div[x$fert == 1],
                    diff_frac = (x$div[x$fert == 0] - x$div[x$fert == 1]) / x$div[x$fert == 0]))
}


q1_spatial_summary <- q1_spatial %>% group_by(site, block, year, samp) %>%
  do(calc_diff(.))

q1_spatial_summary %>% filter(samp == 1 | samp == 64)

q1_spatial_summary %>%
  filter(site != "HREC") %>%
  ggplot(aes(x = as.numeric(samp))) +
  geom_line(aes(y = -diff_frac, linetype = paste(site, block), color = year))+
  ggtitle("difference at q = 1")
```

# Accumulation at q = 2

```{r}
q2_spatial <- reduce(specaccum(2), bind_rows) %>%
  gather(key = "samp", value = "div", -(1:5)) %>%
  filter(! ((site == "HREC") & (block == 1))) 

calc_diff <- function(x){
  return(data.frame(div_u = x$div[x$fert == 0],
                    div_f = x$div[x$fert == 1],
                    diff = x$div[x$fert == 0] - x$div[x$fert == 1],
                    diff_frac = (x$div[x$fert == 0] - x$div[x$fert == 1]) / x$div[x$fert == 0]))
}


q2_spatial_summary <- q2_spatial %>% group_by(site, block, year, samp) %>%
  do(calc_diff(.))

q2_spatial_summary %>% filter(samp == 1 | samp == 64)

q2_spatial_summary %>%
  filter(site != "HREC") %>%
  ggplot(aes(x = as.numeric(samp))) +
  geom_line(aes(y = -diff_frac, linetype = paste(site, block), color = year))+
  ggtitle("difference at q = 2")

```

# Combining to produce a single dataset

```{r}
q0_spatial$q = rep(0, nrow(q0_spatial))
q1_spatial$q = rep(1, nrow(q1_spatial))
q2_spatial$q = rep(2, nrow(q2_spatial))

spatial_perm <- bind_rows(list(q0_spatial, q1_spatial, q2_spatial))
head(spatial_perm)
# write.csv(x = spatial_perm, "spatial_accumulation.csv")
```

# Assembling raw species area curves

Just as a visualization, will assemble species area curves using the standard format - an ANOVA with repeating estimates of diversity at every sampling level.

```{r}
head(spatial_perm)
spatial_perm <- spatial_perm %>% filter(site != "HREC")

grandmean <- spatial_perm %>% filter(fert == 0) %>% group_by(samp, q, year) %>% summarise(meandiv = mean(div))
meaneffect <- spatial_perm %>% group_by(samp, q, site, year, block) %>% summarise(effect = -(div[fert == 0] - div[fert == 1])) %>%
  group_by(samp, q, year) %>% summarise(meaneffect = mean(effect))

inner_join(grandmean, meaneffect) %>%
  filter(q == 2) %>%
  ggplot(aes(x = as.numeric(samp))) +
  geom_line(aes(y = meandiv)) +
  geom_line(aes(y = meandiv + meaneffect)) +
  facet_wrap(~year)

inner_join(grandmean, meaneffect) %>%
  filter(q == 0) %>%
  ggplot(aes(x = as.numeric(samp))) +
  geom_line(aes(y = meaneffect / meandiv)) + 
  facet_wrap(~year)

```


```{r}
library(emmeans)

qval = 0
yearval = 2018

loglogcurve <- function(qval, yearval){
  
  rare.dat  <- spatial_perm %>% filter(q == qval & year == yearval) %>% filter(site != "HREC")

  output <- list()
  
  for(i in unique(rare.dat$samp)){
    
    est <- lm(div ~ factor(fert) + factor(site) + site:factor(block), data = rare.dat[rare.dat$samp == as.numeric(i),])
    
    output[[as.numeric(i)]] <- data.frame(samp = c(i,i), emmeans(est, 'fert'))
  }
  
  p <- bind_rows(output) %>%
    ggplot(aes(x = as.numeric(samp),
           color = factor(fert))) + 
    geom_line(aes(y = emmean), size = 2) +
    geom_line(aes(y = lower.CL), linetype = 2) +
    geom_line(aes(y = upper.CL), linetype = 2) +
    theme_fivethirtyeight()
  
  return(p)
}


# ggsave("Figures/GeneralCurvesQ0_2018.jpeg", plot = loglogcurve(0, 2018), height = 7, width = 10)
# 
# ggsave("Figures/GeneralCurvesQ2_2018.jpeg", plot = loglogcurve(2, 2018), height = 7, width = 10)
# 
# ggsave("Figures/GeneralCurvesQ0_2017.jpeg", plot = loglogcurve(0, 2017), height = 7, width = 10)
# 
# ggsave("Figures/GeneralCurvesQ2_2017.jpeg", plot = loglogcurve(2, 2017), height = 7, width = 10)
```

```{r}
library(lme4)
mod <- lmer(log(div) ~ factor(fert) * log(as.numeric(samp)) + (1|site) + (1|site:block), data = rare.dat)
emmeans(mod, c("samp", "fert"))

```




```{r}
spatial_perm %>% group_by(fert, samp, q, year) %>%
  summarise(meandiv = mean(div)) %>%
  filter(q == 0) %>%
  ggplot(aes(x = as.numeric(samp),
             y = meandiv, 
             color = as.factor(fert))) +
  geom_line(size = 1.5) +
  facet_wrap(~year) +
  theme_fivethirtyeight()

spatial_perm %>% group_by(fert, samp, q, year) %>%
  summarise(meandiv = mean(div)) %>%
  group_by(samp, q, year) %>%
  summarise(propdiff = (meandiv[fert == 0] - meandiv[fert == 1])) %>%
  filter(q == 0) %>%
  ggplot(aes(x = as.numeric(samp),
             y = propdiff,
             color = year)) +
  geom_line()
  # facet_wrap(~year)
```

```{r}
spatial_perm %>% group_by(fert, samp, q, year) %>%
  summarise(meandiv = mean(div),
            semean = sd(div) / sqrt(11)) %>%
  filter(q == 2) %>%
  ggplot(aes(x = as.numeric(samp),
             color = as.factor(fert))) +
  geom_line(aes(y = meandiv), size = 2) +
  geom_line(aes(y = meandiv - semean), linetype = 2 ) +
  geom_line(aes(y = meandiv + semean), linetype = 2) +
  facet_wrap(~year)


spatial_perm %>% group_by(fert, samp, q, year) %>%
  summarise(meandiv = mean(div)) %>%
  group_by(samp, q, year) %>%
  summarise(propdiff = (meandiv[fert == 0] - meandiv[fert == 1])) %>%
  filter(q == 2) %>%
  ggplot(aes(x = as.numeric(samp),
             y = propdiff,
             color = year)) +
  geom_line()
```

