---
title: "Two-scale analysis with permutations"
output: html_notebook
---

```{r}
library(lmPerm)
library(dplyr)
source("ens_specaccum.R")
library(ggplot2)

final_merged <- read.csv("../final_2018.csv", header = TRUE, stringsAsFactors = FALSE)
head(final_merged)[,1:20]
```

```{r}
com.mat <- final_merged %>% select(- one_of("site", "block", "plot", "subplot", "x", "y", 
                                            "note", "index", "year", "sitename", "dateestablished", 
                                            "plotlocation", "fertilized", "X"))
com.attr <-  final_merged %>% select(one_of("site", "block", "plot", "subplot", "x", "y", 
                                            "note", "index", "year", "sitename", "dateestablished", 
                                            "plotlocation", "fertilized"))

dfun = d_calc

com_norm <- normalize_rows(com.mat)
unique(rowSums(com_norm)) == 1

# Sample (alpha) diversity
alpha_q0 = apply(com_norm, 1, dfun, q = 0, sample.weight = 1)
alpha_q1 = apply(com_norm, 1, dfun, q = 1, sample.weight = 1)
alpha_q2 = apply(com_norm, 1, dfun, q = 2, sample.weight = 1)

# Combining alpha statistics to a single dataframe
alpha.stats <- cbind(com.attr, alpha_q0, alpha_q1, alpha_q2) %>% 
  group_by(site, block, plot, fertilized, year) %>%
  summarise_at(c("alpha_q0", "alpha_q1", "alpha_q2"), mean)

alpha.raw <- cbind(com.attr, alpha_q0, alpha_q1, alpha_q2)

# Aggregating to generate gamma diversity matrix
com.gamma <- bind_cols(select(com.attr, site, block, plot, year, fertilized), com.mat) %>% 
  group_by(site, block, plot, year, fertilized) %>%
  summarise_all(sum)

# Generating gamma diversity dataset
gamma.attr <- com.gamma[,1:5]
gamma.norm <- normalize_rows(com.gamma[,-(1:5)])

# Total (gamma) diversity
gamma_q0 = apply(gamma.norm, 1, dfun, q = 0, sample.weight = 1)
gamma_q1 = apply(gamma.norm, 1, dfun, q = 1, sample.weight = 1)
gamma_q2 = apply(gamma.norm, 1, dfun, q = 2, sample.weight = 1)

gamma.stats <- cbind(data.frame(gamma.attr), gamma_q0, gamma_q1, gamma_q2)

# Combining into a single dataframe
alldiv.stats <- inner_join(alpha.stats, gamma.stats) %>%
  mutate(beta_q0 = gamma_q0 / alpha_q0,
         beta_q1 = gamma_q1 / alpha_q1,
         beta_q2 = gamma_q2 / alpha_q2)
```

```{r}

# For a given matrix
permtest_conf <- function(com.mat, com.attr, qval, perm){
  
  require(testthat)
  
  # Take all the rows and split them into two groups
  com.F <- com.mat[com.attr$fertilized == 1,][sample(c(1:64), 64, replace = TRUE),]
  com.UF <- com.mat[com.attr$fertilized == 0,][sample(c(1:64), 64, replace = TRUE),]
  
  # Equal sizes?
  expect_true(nrow(com.F) == nrow(com.UF))
  
  # Normalize, calc alpha diversity of each group and store
  alpha_fert <- apply(normalize_rows(com.F), 1, dfun, q = qval, sample.weight = 1)
  alpha_unfert <- apply(normalize_rows(com.UF), 1, dfun, q = qval, sample.weight = 1)
  
  # Aggregate up to the gamma scale
  gam.F <-apply(com.F, 2, sum)
  gam.UF <- apply(com.UF, 2, sum)
  
  # Calculate gamma level diversity statistics
  gamma_fert = dfun(gam.F/ sum(gam.F), q = qval, sample.weight = 1)
  gamma_unfert = dfun(gam.UF/ sum(gam.UF), q = qval, sample.weight = 1)

  # Calculate beta diversity of each group and store
  beta_fert = gamma_fert / mean(alpha_fert)
  beta_unfert = gamma_unfert / mean(alpha_unfert)

  # Return data set
  return(data.frame(fert = c(1, 0),
                    perm = c(perm, perm),
                    alpha = c(mean(alpha_fert), mean(alpha_unfert)),
                    beta = c(beta_fert, beta_unfert),
                    gamma = c(gamma_fert, gamma_unfert)))
  
}

permtest_conf(com.mat, com.attr, qval = 0, perm = 1)

```

# Repeat for each value of Q

# Q = 0
```{r}

permtest_repeat <- function(com.mat, com.attr, qval, perm, perm.total){
  
  output <- list()
  while(perm < perm.total){
    permstore <- permtest_conf(com.mat, com.attr, qval, perm)
    output[[perm]] <- data.frame(permstore)
    perm <- perm + 1
  }
  return(bind_rows(output))
}

full_perm <- com.attr %>% select(site, block, year, fertilized) %>%
  bind_cols(com.mat) %>%
  group_by(site, block, year) %>%
  do(permtest_repeat(.[,5:ncol(.)], .[,c(1:4)], qval = 0, perm = 1, perm.total = 9999))

write.csv(x = full_perm, "../twoscale_perm_q0_conf.csv")

# perm_summary <- full_perm %>% group_by(site, block, year, perm) %>%
#   summarise(diff_alpha = alpha[fert == 0] - alpha[fert == 1],
#             diff_beta = beta[fert == 0] - beta[fert == 1],
#             diff_gamma = gamma[fert == 0] - gamma[fert == 1])
# 
# perm_summary %>% 
#   ggplot(aes(x = diff_alpha, color = as.factor(year))) +
#   geom_density() +
#   facet_grid(block~site)
```


# Q = 0
```{r}

permtest_repeat <- function(com.mat, com.attr, qval, perm, perm.total){
  
  output <- list()
  while(perm < perm.total){
    permstore <- permtest_conf(com.mat, com.attr, qval, perm)
    output[[perm]] <- data.frame(permstore)
    perm <- perm + 1
  }
  return(bind_rows(output))
}

full_perm <- com.attr %>% select(site, block, year, fertilized) %>%
  bind_cols(com.mat) %>%
  group_by(site, block, year) %>%
  do(permtest_repeat(.[,5:ncol(.)], .[,c(1:4)], qval = 1, perm = 1, perm.total = 9999))

write.csv(x = full_perm, "../twoscale_perm_q1_conf.csv")
# 
# perm_summary <- full_perm %>% group_by(site, block, year, perm) %>%
#   summarise(diff_alpha = alpha[fert == 0] - alpha[fert == 1],
#             diff_beta = beta[fert == 0] - beta[fert == 1],
#             diff_gamma = gamma[fert == 0] - gamma[fert == 1])
# 
# perm_summary %>% 
#   ggplot(aes(x = diff_alpha, color = as.factor(year))) +
#   geom_density() +
#   facet_grid(block~site)
```



# Q = 2
```{r}

permtest_repeat <- function(com.mat, com.attr, qval, perm, perm.total){
  
  output <- list()
  while(perm < perm.total){
    permstore <- permtest_conf(com.mat, com.attr, qval, perm)
    output[[perm]] <- data.frame(permstore)
    perm <- perm + 1
  }
  return(bind_rows(output))
}

full_perm <- com.attr %>% select(site, block, year, fertilized) %>%
  bind_cols(com.mat) %>%
  group_by(site, block, year) %>%
  do(permtest_repeat(.[,5:ncol(.)], .[,c(1:4)], qval = 2, perm = 1, perm.total = 9999))

write.csv(x = full_perm, "../twoscale_perm_q2_conf.csv")

perm_summary <- full_perm %>% group_by(site, block, year, perm) %>%
  summarise(diff_alpha = alpha[fert == 0] - alpha[fert == 1],
            diff_beta = beta[fert == 0] - beta[fert == 1],
            diff_gamma = gamma[fert == 0] - gamma[fert == 1])

perm_summary %>%
  ggplot(aes(x = diff_alpha, color = as.factor(year))) +
  geom_density() +
  facet_grid(block~site)
```